name: Docker Image CI

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set version timestamp
      id: vars
      run: echo "VERSION=$(date +%s)" >> "$GITHUB_OUTPUT"

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GHCR_PAT }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin

    - name: Build the Docker image
      run: |
        IMAGE_ID=ghcr.io/aayush-meshram/typeface-fe
        VERSION=${{ steps.vars.outputs.VERSION }}
        docker build . --file Dockerfile --tag $IMAGE_ID:$VERSION --tag $IMAGE_ID:latest
    - name: Push the Docker image
      run: |
        IMAGE_ID=ghcr.io/aayush-meshram/typeface-fe
        VERSION=${{ steps.vars.outputs.VERSION }}
        docker push $IMAGE_ID:$VERSION
        docker push $IMAGE_ID:latest
